from __future__ import annotations

import gc
import inspect
import warnings
from pathlib import Path
from typing import Any

import pandas as pd

from python_eda_toolkit.preprocessing.loaders import load_data
from python_eda_toolkit.smart.recommender import suggest_models, suggest_preprocessing
from python_eda_toolkit.visualization import generate_auto_plots
from python_eda_toolkit.reporting import generate_html_report


# =========================================================
# MEMORY / PERFORMANCE DEFAULTS
# =========================================================

PROFILE_SAMPLE_ROWS = 50_000
TEXT_SAMPLE_ROWS = 2_000
DATETIME_SAMPLE_ROWS = 500
OUTLIER_SAMPLE_ROWS = 50_000
TARGET_CORR_SAMPLE_ROWS = 50_000
PLOT_SAMPLE_ROWS = 20_000
MAX_PRINT_ROWS = 5


# =========================================================
# PRINT HELPERS
# =========================================================

def _print_section(title: str) -> None:
    print(f"\n{title}")
    print("=" * 60)


def _print_items(items: Any) -> None:
    if not items:
        print("None detected.")
        return

    for item in items:
        print(f"- {item}")


def _get_dataset_name(data: Any) -> str:
    if isinstance(data, (str, Path)):
        return Path(data).name
    return "DataFrame"


def _round(value: Any, decimals: int = 4) -> Any:
    try:
        if pd.isna(value):
            return None
        return round(float(value), decimals)
    except (TypeError, ValueError):
        return value


def _format_mb(value: Any) -> str:
    try:
        return f"{float(value):.2f} MB"
    except (TypeError, ValueError):
        return "N/A"


# =========================================================
# DATAFRAME HELPERS
# =========================================================

def _sample_df(
    df: pd.DataFrame,
    max_rows: int,
    random_state: int = 42,
) -> pd.DataFrame:
    if len(df) <= max_rows:
        return df

    return df.sample(
        n=max_rows,
        random_state=random_state,
    )


def _clean_dataframe_columns(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    """Remove autogenerated index columns and duplicated column names.

    This keeps demos and reports clean when CSV files were saved with an
    index, creating columns such as `Unnamed: 0` or `Unnamed: 0.1`.
    """

    df = df.copy()

    removed_columns: list[str] = []

    unnamed_columns = [
        column
        for column in df.columns
        if str(column).startswith("Unnamed")
    ]

    if unnamed_columns:
        df = df.drop(columns=unnamed_columns)
        removed_columns.extend([str(column) for column in unnamed_columns])

    duplicated_mask = df.columns.duplicated()

    if duplicated_mask.any():
        duplicated_columns = df.columns[duplicated_mask].tolist()
        df = df.loc[:, ~duplicated_mask]
        removed_columns.extend([str(column) for column in duplicated_columns])

    return df, removed_columns


def _optimize_dataframe_memory(df: pd.DataFrame) -> pd.DataFrame:
    """Downcast numeric/bool columns without changing public behavior."""

    df = df.copy()

    for column in df.select_dtypes(include=["float64"]).columns:
        df[column] = pd.to_numeric(df[column], downcast="float")

    for column in df.select_dtypes(include=["int64"]).columns:
        df[column] = pd.to_numeric(df[column], downcast="integer")

    for column in df.select_dtypes(include=["bool"]).columns:
        df[column] = df[column].astype("int8")

    return df


# =========================================================
# VALIDATION
# =========================================================

def _validate_dataframe(df: pd.DataFrame) -> None:
    if df is None:
        raise ValueError("No dataset was loaded.")

    if not isinstance(df, pd.DataFrame):
        raise TypeError("Loaded data must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Dataset is empty.")

    if df.shape[1] == 0:
        raise ValueError("Dataset has no columns.")


def _validate_column(
    df: pd.DataFrame,
    column: str | None,
    column_label: str,
) -> None:
    if column and column not in df.columns:
        raise ValueError(
            f"{column_label} '{column}' not found. "
            f"Available columns: {list(df.columns)}"
        )


# =========================================================
# COLUMN DETECTION
# =========================================================

def _is_object_like(series: pd.Series) -> bool:
    return (
        pd.api.types.is_object_dtype(series)
        or pd.api.types.is_string_dtype(series)
        or isinstance(series.dtype, pd.CategoricalDtype)
    )


def _detect_datetime_columns(df: pd.DataFrame) -> list[str]:
    datetime_columns: list[str] = []

    date_keywords = (
        "date",
        "time",
        "timestamp",
        "created_at",
        "updated_at",
        "year",
        "month",
        "day",
    )

    date_pattern = (
        r"\d{4}[-/]\d{1,2}[-/]\d{1,2}"
        r"|"
        r"\d{1,2}[-/]\d{1,2}[-/]\d{2,4}"
    )

    for column in df.columns:
        series = df[column]

        if pd.api.types.is_datetime64_any_dtype(series):
            datetime_columns.append(column)
            continue

        if not _is_object_like(series):
            continue

        column_lower = str(column).lower()
        has_date_name = any(keyword in column_lower for keyword in date_keywords)

        sample = series.dropna().astype(str).head(DATETIME_SAMPLE_ROWS)

        if sample.empty:
            continue

        looks_like_date = sample.str.contains(
            date_pattern,
            regex=True,
        ).mean() >= 0.60

        if not has_date_name and not looks_like_date:
            continue

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            converted = pd.to_datetime(sample, errors="coerce")

        if converted.notna().mean() >= 0.80:
            datetime_columns.append(column)

    return datetime_columns


def _detect_text_columns(df: pd.DataFrame) -> list[str]:
    text_columns: list[str] = []

    object_columns = df.select_dtypes(
        include=["object", "string"],
    ).columns

    for column in object_columns:
        sample = df[column].dropna().astype(str).head(TEXT_SAMPLE_ROWS)

        if sample.empty:
            continue

        avg_length = sample.str.len().mean()
        unique_ratio = sample.nunique(dropna=True) / max(len(sample), 1)

        if avg_length >= 40 and unique_ratio >= 0.50:
            text_columns.append(column)

    return text_columns


def _detect_id_columns(df: pd.DataFrame) -> list[str]:
    id_columns: list[str] = []
    rows = max(len(df), 1)

    for column in df.columns:
        column_lower = str(column).lower()
        series = df[column]

        explicit_id = (
            column_lower == "id"
            or column_lower.endswith("_id")
            or column_lower in {"uuid", "guid"}
        )

        high_cardinality_text = (
            rows >= 500
            and _is_object_like(series)
            and series.nunique(dropna=True) / rows >= 0.98
        )

        if explicit_id or high_cardinality_text:
            id_columns.append(column)

    return id_columns


def _detect_constant_columns(df: pd.DataFrame) -> list[str]:
    return [
        column
        for column in df.columns
        if df[column].nunique(dropna=False) <= 1
    ]


def _detect_high_cardinality_columns(
    df: pd.DataFrame,
    max_ratio: float = 0.50,
    min_unique: int = 30,
) -> list[str]:
    high_cardinality: list[str] = []

    object_columns = df.select_dtypes(
        include=["object", "string", "category"],
    ).columns

    for column in object_columns:
        non_missing = df[column].dropna()

        if non_missing.empty:
            continue

        unique_count = non_missing.nunique(dropna=True)
        unique_ratio = unique_count / max(len(non_missing), 1)

        if unique_count >= min_unique and unique_ratio >= max_ratio:
            high_cardinality.append(column)

    return high_cardinality


def _detect_column_types(df: pd.DataFrame) -> dict[str, list[str]]:
    # Expensive type detection is done on a bounded sample, while simple dtype
    # lists still use the full dataframe.
    sample = _sample_df(df, PROFILE_SAMPLE_ROWS)

    datetime_columns = _detect_datetime_columns(sample)
    text_columns = _detect_text_columns(sample)
    id_columns = _detect_id_columns(sample)

    numeric_columns = df.select_dtypes(include=["number"]).columns.tolist()
    boolean_columns = df.select_dtypes(include=["bool"]).columns.tolist()

    categorical_columns = [
        column
        for column in df.select_dtypes(
            include=["object", "string", "category", "bool"],
        ).columns.tolist()
        if column not in datetime_columns
        and column not in text_columns
    ]

    return {
        "numeric": numeric_columns,
        "categorical": categorical_columns,
        "datetime": datetime_columns,
        "text": text_columns,
        "boolean": boolean_columns,
        "id": id_columns,
        "constant": _detect_constant_columns(sample),
        "high_cardinality": _detect_high_cardinality_columns(sample),
    }


# =========================================================
# TASK DETECTION
# =========================================================

def _detect_problem_type(
    df: pd.DataFrame,
    target: str | None = None,
    date_column: str | None = None,
    user_column: str | None = None,
    item_column: str | None = None,
    task_type: str = "auto",
) -> str:
    valid_task_types = {
        "auto",
        "exploratory",
        "classification",
        "regression",
        "time_series",
        "recommendation",
        "nlp",
    }

    if task_type not in valid_task_types:
        raise ValueError(
            f"Invalid task_type '{task_type}'. "
            f"Valid values are: {sorted(valid_task_types)}"
        )

    if task_type != "auto":
        return task_type

    if user_column and item_column:
        return "recommendation"

    if date_column:
        return "time_series"

    if target is None:
        sampled_df = _sample_df(df, PROFILE_SAMPLE_ROWS)
        return "nlp" if _detect_text_columns(sampled_df) else "exploratory"

    y = df[target].dropna()

    if y.empty:
        return "exploratory"

    unique_values = y.nunique(dropna=True)
    unique_ratio = unique_values / max(len(y), 1)

    if not pd.api.types.is_numeric_dtype(y):
        return "classification"

    if unique_values <= 20 or unique_ratio <= 0.05:
        return "classification"

    return "regression"


# =========================================================
# SUMMARIES
# =========================================================

def _summarize_missing_values(
    df: pd.DataFrame,
    top_n: int = 10,
) -> list[str]:
    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    if missing.empty:
        return []

    total_rows = max(len(df), 1)

    return [
        f"{column}: {int(count)} missing "
        f"({round((count / total_rows) * 100, 2)}%)"
        for column, count in missing.head(top_n).items()
    ]


def _summarize_column_types(column_types: dict[str, list[str]]) -> list[str]:
    return [
        f"Numeric columns: {len(column_types['numeric'])}",
        f"Categorical columns: {len(column_types['categorical'])}",
        f"Datetime columns: {len(column_types['datetime'])}",
        f"Text columns: {len(column_types['text'])}",
        f"Boolean columns: {len(column_types['boolean'])}",
        f"Potential ID columns: {len(column_types['id'])}",
        f"Constant columns: {len(column_types['constant'])}",
        f"High-cardinality columns: {len(column_types['high_cardinality'])}",
    ]


def _summarize_classification_target(
    df: pd.DataFrame,
    target: str,
    top_n: int = 20,
) -> list[str]:
    distribution = df[target].value_counts(dropna=False)
    percentages = (
        df[target]
        .value_counts(normalize=True, dropna=False)
        .mul(100)
        .round(2)
    )

    summary = [
        f"{value}: {count} rows ({percentages.loc[value]}%)"
        for value, count in distribution.head(top_n).items()
    ]

    if len(distribution) > top_n:
        summary.append(
            f"... {len(distribution) - top_n} additional classes not shown."
        )

    return summary


def _summarize_regression_target(
    df: pd.DataFrame,
    target: str,
) -> list[str]:
    series = df[target].dropna()

    if series.empty:
        return ["Target contains only missing values."]

    return [
        f"Count: {int(series.count())}",
        f"Mean: {round(series.mean(), 4)}",
        f"Median: {round(series.median(), 4)}",
        f"Standard deviation: {round(series.std(), 4)}",
        f"Minimum: {round(series.min(), 4)}",
        f"Maximum: {round(series.max(), 4)}",
        f"Skewness: {round(series.skew(), 4)}",
        f"Unique values: {series.nunique(dropna=True)}",
    ]


def _summarize_target(
    df: pd.DataFrame,
    target: str | None,
    problem_type: str,
) -> list[str]:
    if not target:
        return []

    if problem_type == "classification":
        return _summarize_classification_target(df, target)

    if problem_type in {"regression", "time_series"} and pd.api.types.is_numeric_dtype(df[target]):
        return _summarize_regression_target(df, target)

    return [
        f"Unique values: {df[target].nunique(dropna=True)}",
        f"Missing target values: {int(df[target].isnull().sum())}",
    ]


# =========================================================
# SMART PROFILE
# =========================================================

def _calculate_outlier_summary(
    df: pd.DataFrame,
    numeric_columns: list[str] | None = None,
) -> list[dict[str, Any]]:
    work_df = _sample_df(df, OUTLIER_SAMPLE_ROWS)
    numeric_columns = numeric_columns or work_df.select_dtypes(
        include=["number"],
    ).columns.tolist()

    summary: list[dict[str, Any]] = []

    for column in numeric_columns:
        if column not in work_df.columns:
            continue

        series = work_df[column].dropna()

        if series.empty or series.nunique(dropna=True) <= 1:
            continue

        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)
        iqr = q3 - q1

        if iqr == 0 or pd.isna(iqr):
            continue

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        count = int(((series < lower) | (series > upper)).sum())

        if count > 0:
            estimated_count = int(round(count * (len(df) / len(work_df))))
            summary.append(
                {
                    "column": column,
                    "outliers": estimated_count,
                    "outlier_ratio": _round(count / max(len(series), 1), 4),
                }
            )

    return sorted(summary, key=lambda item: item["outliers"], reverse=True)


def _calculate_skewness_summary(
    df: pd.DataFrame,
    numeric_columns: list[str] | None = None,
    threshold: float = 1.0,
) -> list[dict[str, Any]]:
    work_df = _sample_df(df, OUTLIER_SAMPLE_ROWS)
    numeric_columns = numeric_columns or work_df.select_dtypes(
        include=["number"],
    ).columns.tolist()

    summary: list[dict[str, Any]] = []

    for column in numeric_columns:
        if column not in work_df.columns:
            continue

        series = work_df[column].dropna()

        if series.empty or series.nunique(dropna=True) <= 1:
            continue

        skewness = series.skew()

        if pd.notna(skewness) and abs(skewness) >= threshold:
            summary.append(
                {
                    "column": column,
                    "skewness": _round(skewness, 4),
                }
            )

    return sorted(
        summary,
        key=lambda item: abs(item["skewness"]),
        reverse=True,
    )


def _calculate_target_correlations(
    df: pd.DataFrame,
    target: str | None,
    numeric_columns: list[str] | None = None,
    top_n: int = 8,
) -> list[dict[str, Any]]:
    if not target or target not in df.columns:
        return []

    if not pd.api.types.is_numeric_dtype(df[target]):
        return []

    work_df = _sample_df(df, TARGET_CORR_SAMPLE_ROWS)
    numeric_columns = numeric_columns or work_df.select_dtypes(
        include=["number"],
    ).columns.tolist()

    candidate_columns = [column for column in numeric_columns if column != target]
    correlations: list[dict[str, Any]] = []

    for column in candidate_columns:
        if column not in work_df.columns:
            continue

        data = work_df[[column, target]].dropna()

        if data.empty or data[column].nunique() <= 1 or data[target].nunique() <= 1:
            continue

        corr = data[column].corr(data[target])

        if pd.notna(corr):
            correlations.append(
                {
                    "feature": column,
                    "correlation": _round(corr, 4),
                    "abs_correlation": abs(corr),
                }
            )

    return sorted(
        correlations,
        key=lambda item: item["abs_correlation"],
        reverse=True,
    )[:top_n]


def _build_data_profile(
    df: pd.DataFrame,
    target: str | None = None,
    column_types: dict[str, list[str]] | None = None,
    problem_type: str | None = None,
) -> dict[str, Any]:
    column_types = column_types or _detect_column_types(df)

    missing_by_column = df.isnull().sum()
    missing_by_column = missing_by_column[missing_by_column > 0].sort_values(
        ascending=False,
    )

    numeric_columns = column_types["numeric"]
    total_missing = int(missing_by_column.sum())
    duplicate_rows = int(df.duplicated().sum())

    return {
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "total_missing": total_missing,
        "missing_ratio": _round(
            total_missing / max(df.shape[0] * df.shape[1], 1),
            4,
        ),
        "duplicate_rows": duplicate_rows,
        "duplicate_ratio": _round(
            duplicate_rows / max(len(df), 1),
            4,
        ),
        "memory_mb": _round(
            df.memory_usage(deep=True).sum() / 1024**2,
            2,
        ),
        "problem_type": problem_type,
        "target": target,
        "column_types": column_types,
        "missing_by_column": [
            {
                "column": column,
                "missing": int(count),
                "missing_ratio": _round(count / max(len(df), 1), 4),
            }
            for column, count in missing_by_column.items()
        ],
        "outliers": _calculate_outlier_summary(df, numeric_columns=numeric_columns),
        "skewness": _calculate_skewness_summary(df, numeric_columns=numeric_columns),
        "target_correlations": _calculate_target_correlations(
            df,
            target,
            numeric_columns=numeric_columns,
        ),
    }


def _generate_dataset_warnings(
    df: pd.DataFrame,
    target: str | None = None,
    column_types: dict[str, list[str]] | None = None,
    problem_type: str | None = None,
    data_profile: dict[str, Any] | None = None,
) -> list[dict[str, str]]:
    column_types = column_types or _detect_column_types(df)
    data_profile = data_profile or _build_data_profile(
        df,
        target,
        column_types,
        problem_type,
    )

    warnings_list: list[dict[str, str]] = []

    duplicate_count = data_profile["duplicate_rows"]
    duplicate_ratio = data_profile["duplicate_ratio"] or 0
    total_missing = data_profile["total_missing"]
    missing_ratio = data_profile["missing_ratio"] or 0

    if duplicate_count > 0:
        warnings_list.append(
            {
                "level": "danger" if duplicate_ratio >= 0.05 else "warning",
                "title": "Duplicate rows",
                "message": (
                    f"{duplicate_count} duplicate rows detected "
                    f"({duplicate_ratio:.2%})."
                ),
            }
        )

    if total_missing > 0:
        warnings_list.append(
            {
                "level": "danger" if missing_ratio >= 0.05 else "warning",
                "title": "Missing values",
                "message": f"{total_missing} missing cells detected ({missing_ratio:.2%}).",
            }
        )

    if target and target in df.columns:
        target_missing = int(df[target].isnull().sum())

        if target_missing > 0:
            warnings_list.append(
                {
                    "level": "danger",
                    "title": "Missing target values",
                    "message": (
                        f"Target column '{target}' contains "
                        f"{target_missing} missing values."
                    ),
                }
            )

        if problem_type == "classification":
            class_ratio = df[target].value_counts(normalize=True, dropna=True)

            if not class_ratio.empty and class_ratio.max() > 0.70:
                warnings_list.append(
                    {
                        "level": "warning",
                        "title": "Potential class imbalance",
                        "message": (
                            f"The largest class represents "
                            f"{class_ratio.max():.2%} of known target values."
                        ),
                    }
                )

    if column_types["constant"]:
        warnings_list.append(
            {
                "level": "warning",
                "title": "Constant columns",
                "message": (
                    "Remove columns with a single value: "
                    f"{column_types['constant'][:8]}."
                ),
            }
        )

    if column_types["id"]:
        warnings_list.append(
            {
                "level": "warning",
                "title": "Potential ID columns",
                "message": (
                    "Exclude ID-like columns from model features: "
                    f"{column_types['id'][:8]}."
                ),
            }
        )

    if column_types["high_cardinality"]:
        warnings_list.append(
            {
                "level": "warning",
                "title": "High-cardinality categoricals",
                "message": (
                    "Avoid naive one-hot encoding for: "
                    f"{column_types['high_cardinality'][:8]}."
                ),
            }
        )

    if column_types["datetime"]:
        warnings_list.append(
            {
                "level": "warning",
                "title": "Datetime columns",
                "message": (
                    "Consider temporal features and chronological validation "
                    "if the task is time-based."
                ),
            }
        )

    if column_types["text"]:
        warnings_list.append(
            {
                "level": "warning",
                "title": "Text columns",
                "message": (
                    "Text-like columns may require NLP preprocessing: "
                    f"{column_types['text'][:8]}."
                ),
            }
        )

    if data_profile["outliers"]:
        top = data_profile["outliers"][0]
        warnings_list.append(
            {
                "level": "warning",
                "title": "Numerical outliers",
                "message": (
                    f"'{top['column']}' contains approximately "
                    f"{top['outliers']} IQR-based outliers."
                ),
            }
        )

    return warnings_list or [
        {
            "level": "success",
            "title": "No important warnings",
            "message": "No major structural quality risks were detected.",
        }
    ]


def _generate_smart_insights(
    df: pd.DataFrame,
    target: str | None = None,
    column_types: dict[str, list[str]] | None = None,
    problem_type: str | None = None,
    data_profile: dict[str, Any] | None = None,
) -> list[str]:
    column_types = column_types or _detect_column_types(df)
    data_profile = data_profile or _build_data_profile(
        df,
        target,
        column_types,
        problem_type,
    )

    insights: list[str] = []

    if data_profile["missing_by_column"]:
        top = data_profile["missing_by_column"][0]
        insights.append(
            f"Column '{top['column']}' has the highest missingness: "
            f"{top['missing']} values ({top['missing_ratio']:.2%})."
        )

    if data_profile["target_correlations"]:
        top = data_profile["target_correlations"][0]
        direction = "positive" if top["correlation"] >= 0 else "negative"
        insights.append(
            f"'{top['feature']}' has the strongest linear relationship "
            f"with the target ({direction}: {top['correlation']})."
        )

    if data_profile["skewness"]:
        top = data_profile["skewness"][0]
        insights.append(
            f"'{top['column']}' is highly skewed "
            f"(skewness: {top['skewness']})."
        )

    if data_profile["outliers"]:
        top = data_profile["outliers"][0]
        insights.append(
            f"'{top['column']}' shows the highest number of IQR-based "
            f"outliers ({top['outliers']})."
        )

    if problem_type:
        insights.append(f"Detected analytical setup: {problem_type}.")

    if column_types["numeric"] and column_types["categorical"]:
        insights.append(
            "The dataset contains numerical and categorical features, "
            "so preprocessing should be model-specific."
        )

    return list(dict.fromkeys(insights))[:8]


def _generate_next_steps(
    df: pd.DataFrame,
    target: str | None = None,
    problem_type: str | None = None,
    column_types: dict[str, list[str]] | None = None,
    data_profile: dict[str, Any] | None = None,
    preprocessing_suggestions: list[str] | None = None,
    model_suggestions: list[str] | None = None,
) -> list[str]:
    column_types = column_types or _detect_column_types(df)
    data_profile = data_profile or _build_data_profile(
        df,
        target,
        column_types,
        problem_type,
    )

    steps: list[str] = []

    if data_profile["total_missing"] > 0:
        steps.append(
            "Review missing values and choose imputation or row removal before training."
        )

    if data_profile["duplicate_rows"] > 0:
        steps.append(
            "Confirm whether duplicate rows are valid observations or should be removed."
        )

    if column_types["constant"]:
        steps.append(
            "Remove constant columns because they do not add predictive information."
        )

    if column_types["id"]:
        steps.append("Exclude ID-like columns from standard model features.")

    if column_types["high_cardinality"]:
        steps.append(
            "Use rare-category grouping, frequency encoding or target encoding "
            "for high-cardinality categoricals."
        )
    elif column_types["categorical"]:
        steps.append("Encode low-cardinality categorical variables with one-hot encoding.")

    if column_types["numeric"]:
        steps.append(
            "Scale numerical features for linear, distance-based or gradient-based models."
        )

    if data_profile["outliers"]:
        steps.append(
            "Inspect numerical outliers and decide whether to keep, cap or transform them."
        )

    if problem_type in {"classification", "regression"} and target:
        steps.append(
            "Create a train/test split and keep the test set untouched for final evaluation."
        )

    if model_suggestions:
        steps.append(
            "Start with the simplest baseline, then compare stronger candidate models."
        )

    return list(dict.fromkeys(steps))[:8]


def _build_report_payload(
    df: pd.DataFrame,
    dataset_name: str,
    target: str | None,
    problem_type: str,
    column_types: dict[str, list[str]],
    data_profile: dict[str, Any],
    preprocessing_suggestions: list[str],
    model_suggestions: list[str],
) -> dict[str, Any]:
    return {
        "dataset_name": dataset_name,
        "dataset_shape": df.shape,
        "missing_values": data_profile["total_missing"],
        "preprocessing_suggestions": preprocessing_suggestions,
        "model_suggestions": model_suggestions,
        "problem_type": problem_type,
        "target": target,
        "column_types": column_types,
        "data_profile": data_profile,
        "dataset_warnings": _generate_dataset_warnings(
            df,
            target,
            column_types,
            problem_type,
            data_profile,
        ),
        "smart_insights": _generate_smart_insights(
            df,
            target,
            column_types,
            problem_type,
            data_profile,
        ),
        "next_steps": _generate_next_steps(
            df,
            target,
            problem_type,
            column_types,
            data_profile,
            preprocessing_suggestions,
            model_suggestions,
        ),
    }


def _call_generate_html_report(
    report_payload: dict[str, Any],
    report_path: str,
) -> Any:
    report_payload = dict(report_payload)
    report_payload["output_path"] = report_path

    try:
        signature = inspect.signature(generate_html_report)
        accepted = set(signature.parameters)
        filtered_payload = {
            key: value
            for key, value in report_payload.items()
            if key in accepted
        }
        return generate_html_report(**filtered_payload)

    except (TypeError, ValueError):
        fallback_payload = {
            "dataset_name": report_payload["dataset_name"],
            "dataset_shape": report_payload["dataset_shape"],
            "missing_values": report_payload["missing_values"],
            "preprocessing_suggestions": report_payload["preprocessing_suggestions"],
            "model_suggestions": report_payload["model_suggestions"],
            "output_path": report_path,
        }
        return generate_html_report(**fallback_payload)


# =========================================================
# MAIN FUNCTION
# =========================================================

def auto_analyze(
    data,
    target: str | None = None,
    task_type: str = "auto",
    date_column: str | None = None,
    user_column: str | None = None,
    item_column: str | None = None,
    text_columns: list[str] | None = None,
    plots: bool = False,
    save_plots: bool = False,
    export_html: bool = False,
    report_path: str = "reports/analysis_report.html",
    return_profile: bool = False,
    optimize_memory: bool = True,
    clean_columns: bool = True,
    plot_sample_rows: int = PLOT_SAMPLE_ROWS,
):
    """
    Automatically load and analyze a dataset.

    Memory-friendly behavior:
    - removes autogenerated CSV index columns by default;
    - downcasts numeric columns by default;
    - uses bounded samples for expensive profiling checks;
    - uses a sample for plots on large datasets;
    - avoids repeated full-dataset scans where possible.
    """

    dataset_name = _get_dataset_name(data)
    df = load_data(data)

    _validate_dataframe(df)

    removed_columns: list[str] = []

    if clean_columns:
        df, removed_columns = _clean_dataframe_columns(df)
        _validate_dataframe(df)

    if optimize_memory:
        df = _optimize_dataframe_memory(df)

    _validate_column(df, target, "Target column")
    _validate_column(df, date_column, "Date column")
    _validate_column(df, user_column, "User column")
    _validate_column(df, item_column, "Item column")

    column_types = _detect_column_types(df)

    if text_columns:
        for column in text_columns:
            _validate_column(df, column, "Text column")

        column_types["text"] = list(
            dict.fromkeys(column_types["text"] + list(text_columns))
        )
        column_types["categorical"] = [
            column
            for column in column_types["categorical"]
            if column not in column_types["text"]
        ]

    detected_problem_type = _detect_problem_type(
        df=df,
        target=target,
        date_column=date_column,
        user_column=user_column,
        item_column=item_column,
        task_type=task_type,
    )

    data_profile = _build_data_profile(
        df=df,
        target=target,
        column_types=column_types,
        problem_type=detected_problem_type,
    )

    # =====================================================
    # CONSOLE REPORT
    # =====================================================

    _print_section("Dataset Overview")
    print(f"Dataset : {dataset_name}")
    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")
    print(f"Memory  : {_format_mb(data_profile['memory_mb'])}")

    if removed_columns:
        print(f"Cleaned : removed {removed_columns}")

    _print_section("Dataset Preview")
    print(df.head(MAX_PRINT_ROWS))

    _print_section("Detected Task Type")
    print(detected_problem_type)

    _print_section("Detected Column Types")
    _print_items(_summarize_column_types(column_types))

    target_summary = _summarize_target(df, target, detected_problem_type)

    if target_summary:
        _print_section("Target Summary")
        _print_items(target_summary)

    dataset_warnings = _generate_dataset_warnings(
        df,
        target,
        column_types,
        detected_problem_type,
        data_profile,
    )

    smart_insights = _generate_smart_insights(
        df,
        target,
        column_types,
        detected_problem_type,
        data_profile,
    )

    _print_section("Dataset Warnings")
    _print_items([f"{item['title']}: {item['message']}" for item in dataset_warnings])

    _print_section("Smart Insights")
    _print_items(smart_insights)

    preprocessing_suggestions = suggest_preprocessing(df)

    _print_section("Preprocessing Suggestions")
    _print_items(preprocessing_suggestions)

    model_suggestions: list[str] = []

    if target:
        try:
            model_suggestions = suggest_models(
                df,
                target=target,
                date_column=date_column,
                user_column=user_column,
                item_column=item_column,
            )
        except TypeError:
            model_suggestions = suggest_models(df, target=target)
        except Exception:
            model_suggestions = []

    _print_section("Recommended Models")
    _print_items(model_suggestions) if model_suggestions else print("No model recommendations available.")

    next_steps = _generate_next_steps(
        df,
        target,
        detected_problem_type,
        column_types,
        data_profile,
        preprocessing_suggestions,
        model_suggestions,
    )

    _print_section("Recommended Next Steps")
    _print_items(next_steps)

    # =====================================================
    # PLOTS
    # =====================================================

    if plots or save_plots:
        try:
            plot_df = _sample_df(df, plot_sample_rows)

            generate_auto_plots(
                plot_df,
                target=target,
                task_type=detected_problem_type,
                date_column=date_column,
                save_plots=save_plots,
                show=plots,
            )

            del plot_df
            gc.collect()

        except Exception as error:
            _print_section("Visualization Warning")
            print(f"Plots could not be generated: {error}")

    # =====================================================
    # HTML REPORT
    # =====================================================

    report_payload = _build_report_payload(
        df,
        dataset_name,
        target,
        detected_problem_type,
        column_types,
        data_profile,
        preprocessing_suggestions,
        model_suggestions,
    )

    report_payload["dataset_warnings"] = dataset_warnings
    report_payload["smart_insights"] = smart_insights
    report_payload["next_steps"] = next_steps
    report_payload["removed_columns"] = removed_columns

    if export_html:
        try:
            _call_generate_html_report(report_payload, report_path)
        except Exception as error:
            _print_section("HTML Report Warning")
            print(f"HTML report could not be generated: {error}")

    _print_section("Analysis Complete")

    if return_profile:
        report_payload["dataframe"] = df
        report_payload["target_summary"] = target_summary
        return report_payload

    return df
